### ISSUE TITLE
Add Fox Image to Frontpage Header

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/sumo-playstore-campaign#11]
https://pbs.twimg.com/profile_images/512632004550987776/nQ8akE0b_400x400.png

**Comment by plwt** [comment]
Since this is about a mobile version of Firefox, would this be better?

https://static-media-prod-cdn.sumo.mozilla.net/static/sumo/img/gi-hero-kb.610c805f06cf.png

I also have copies of all of the images of Kit without colour (more like a pencil sketch) if that would help.

**Comment by MichaelKohler** [comment]
Thanks for the suggestion, I don't think I'll come around to implement this in a nice way. I'm closing this as WONTFIX.
