### ISSUE TITLE
Some Events Have No Registration 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/sumo-playstore-campaign#18]
A number of the "Book Your Seat" buttons  take me to -> https://reps.mozilla.org/e/firefox-support-sprint-united-states/
Where there isn't anywhere to register :( 

We should maybe add a note that for Reps events people don't need to rsvp, or ask ppl to use a meet-up or eventbrite page...

**Comment by MichaelKohler** [comment]
@LucyeoH Maybe we can just call the link "Details"? I'm sure not everyone needs an exact RSVP count.

**Comment by LucyeoH-zz** [comment]
@MichaelKohler yep that's smart. Please ignore my pull request to change "Book your seat" to "RSVP" and change the text to "details"

**Comment by MichaelKohler** [comment]
Sounds good to me.
