### ISSUE TITLE
Change "Book Your Seat" to "RSVP"

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/sumo-playstore-campaign#19]
Book your seat is a really weird call to action to ask people to rsvp or register for an event. It sounds like they're buying a bus ticket... 

I recommend changing the button text to "RSVP" or "Register".

**Comment by LucyeoH-zz** [comment]
I did a pull request and solved my own problem!!

**Comment by MichaelKohler** [comment]
I don't see the PR showing up though, did you comment here before you did it or is there a problem somewhere? :/
