### ISSUE TITLE
My edits on the FAQ keep dissapearing

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/sumo-playstore-campaign#24]
@MichaelKohler I've tried to update the FAQ twice but after I press submit I think my pull request disappears, are you rejecting them or am I somehow doing this wrong.... can you help me find my edits?

**Comment by MichaelKohler** [comment]
@LucyeoH I'm not seeing any PRs from you :/

**Comment by MichaelKohler** [comment]
What happens when you click here: https://github.com/mozilla/sumo-playstore-campaign/compare/master...LucyeoH:patch-4 and choose "create pull request"?

**Comment by LucyeoH-zz** [comment]
It showed me my request!! I hit "create pull request" so I think it worked now?

**Comment by MichaelKohler** [comment]
All good
