### ISSUE TITLE
Minimize Text on Landing Page

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/sumo-playstore-campaign#26]
I feel like our landing page looks like it has a LOT of text and I'm a native english speaker... like if we compare the old to this one. 

I'd propose cutting down the text below

"Help users get a better experience" (updated to ->) "Help users have a better experience" 
To just the second paragraph slightly ammended:
" Help users who are asking for support in reviews on the Play store by participating in the Firefox Support Sprint. Join Mozillians around the world for a week of answering questions and helping users have a great experience!"

<img width="1131" alt="screen shot 2018-05-29 at 11 45 39 am" src="https://user-images.githubusercontent.com/8070833/40669901-ffd3838a-6335-11e8-88e5-14f50e458929.png">

To: 

<img width="1114" alt="screen shot 2018-05-29 at 11 45 51 am" src="https://user-images.githubusercontent.com/8070833/40669906-010f1f34-6336-11e8-9e51-4c94ceef42df.png">

@couci @MichaelKohler what do you think?

**Comment by MichaelKohler** [comment]
Sounds good to me, you are always welcome to change the text you added yourself ;)

**Comment by couci** [comment]
@LucyeoH LGTM go aheadn and do  a PR

**Comment by LucyeoH-zz** [comment]
@MichaelKohler yep just wanted to make sure it made sense to you and K first. PR on it's way!

**Comment by MichaelKohler** [comment]
PR merged
