### ISSUE TITLE
Add a Disclaimer that the Tool is a Prototype

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/sumo-playstore-campaign#28]
Hey! George suggested somewhere on the site we have a disclaimer that the tool is still a prototype with a link to this GitHub issue where people can file issues. What do you think?

**Comment by MichaelKohler** [comment]
Sounds good to me, we can add it to the (yet to be released) contribute page?

**Comment by LucyeoH-zz** [comment]
That sounds good!

**Comment by MichaelKohler** [comment]
Do you want to write a short text or do you want me to come up with something?

**Comment by LucyeoH-zz** [comment]
Something like...

"Please note this tool is a prototype and so may still have a few
bugs - file a bug or suggest an improvement here" (link to this github)
