### ISSUE TITLE
Edit page title to SUMO instead of Sumo

### ISSUE THREAD

**Issue by dauntlessnomad** [mozilla/sumo-playstore-campaign#30]
page title now showing  org.mozilla.firefox Review id :12345 sumo which is tooo long.

**Comment by dauntlessnomad** [comment]
the team is fast. fixed it already

**Comment by plwt** [comment]
Would be really nice if it used SUMO instead of Sumo or SuMo.

**Comment by MichaelKohler** [comment]
Fully agree, assigning to Konstantina to tell the devs.

**Comment by MichaelKohler** [comment]
This is done! woop woop
