### ISSUE TITLE
incorrect android and firefox version

### ISSUE THREAD

**Issue by dauntlessnomad** [mozilla/sumo-playstore-campaign#34]
every device version is oreo and firefox version is 59.0.2

**Comment by MichaelKohler** [comment]
That's something for the devs, assigning to Konstantina

**Comment by plwt** [comment]
I have just seen this one myself, kinda scary not having accurate information.

**Comment by rtanglao** [comment]
I supplied the Firefox version in my CSV that I gave to the developers, so the Firefox version is definitely a bug methinks.

**Comment by rtanglao** [comment]
1. the Android Operating system version e.g. oreo is NOT in the CSVs that Google supplies! Therefore  it's also not in the CSV i supplied
2. You can find the CSV that I supplied here (if you are an NDA'd mozillian or MoCo employee I can give you the password via slack):
https://github.com/rtanglao/rt-open-innovation-fennec-gplay/blob/master/27may2018-14nov2017-27may2018-unanswered-reviews-archive.zip

**Comment by MichaelKohler** [comment]
@couci I didn't see this happening anymore, can we close this?

**Comment by couci** [comment]
yes this is fixed, closing
