### ISSUE TITLE
Answer marked as approved even though moderator said "no" to "Positive tone"

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/sumo-playstore-campaign#38]
According to the criteria, "positive tone" needs to have 3/3 votes. I have just put positive tone = "no" to a response, nevertheless it is marked as "approved" in the backend:

![photo5807873383352872524](https://user-images.githubusercontent.com/330324/40878415-14d09350-6691-11e8-8530-62e6c2885010.jpg)

@couci as requested, this is P1.

**Comment by MichaelKohler** [comment]
@couci what's the status on this one?

**Comment by couci** [comment]
this was fixed all all the approved and rejected responses got re-scored.

I am closing
