### ISSUE TITLE
Missing user names

### ISSUE THREAD

**Issue by plwt** [mozilla/sumo-playstore-campaign#40]
I am unable to personalise the greeting as the username is not shown.

**Comment by couci** [comment]
Hey Seburo,
unfortunately we can't get that data from the API (this is a playstore limitation). So there is nothing we can do on this version of the experiment

**Comment by NoahSUMO** [comment]
Also some Google Play reviews have no names b/c the reviewers never set them in the first place & leave them blank. So if we ever are able to get this data in the future, that should be kept in mind as well. :)
