### ISSUE TITLE
Do playstore responses have a max. length?

### ISSUE THREAD

**Issue by Djfe** [mozilla/sumo-playstore-campaign#44]
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1466321

I just saw a response that seems to be cut off.
![screenshot_20180602-140113_01](https://user-images.githubusercontent.com/5685512/41010754-b532d39e-6939-11e8-91c7-cd96acac19ee.png)
has the support user send it that way or was the response cut off by the backend?
(cons -> consider)

How should I vote for this response?
Hasn't addressed the issue, because it's incomplete? (it has addressed the issue fairly well apart from that)

It would be nice if we could edit the replies and then ask the original support user to accept or reject our changes. (if we have ideas what else could be helpful to the user)
or if we could comment on replies

**Comment by rtanglao** [comment]
yes playstore responses are maximum 350 characters

**Comment by Djfe** [comment]
ok
Does the Website limit the textarea to 350 characters? or does the backend cut off too long responses without feedback to the user?

**Comment by MichaelKohler** [comment]
@couci can we make sure the tool actually does inform the responder if it's too long? I think though that this is the same response as I complained about.

**Comment by couci** [comment]
so the website doesn't permit you to post if you are over 350 so I guess the user caught it.

**Comment by Djfe** [comment]
Is it correct that newlines count as two chars? \r\n?
Does Google ignore them when calculating 350 chars?
Does Google ignore URLs when calculating?
Would \n be enough for Google? (We could save a few chars for the response that way)
