### ISSUE TITLE
Count of reviewed responses is wrong/updating asynchronously

### ISSUE THREAD

**Issue by Djfe** [mozilla/sumo-playstore-campaign#45]
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1466323

I reviewed several responses on
https://supportusers.mozilla.community/

It kept on saying:
"Cool. You reviewed already 1 response."
afterwards, even though I reviewed more than one.

It would be nice to see the actual. number there.

![screenshot_20180602-141007_01](https://user-images.githubusercontent.com/5685512/41010935-9b38d406-693a-11e8-9ccf-5f0bda5458cd.png)

(Some time later)
Interesting now it shows "9" (but stays there even though I keep on moderating)

Does it update in intervals or asynchronously or something like that?

**Comment by couci** [comment]
This is the same with #37 fyi it's a cache problem and it is getting fixed
