### ISSUE TITLE
Translation: context/questions

### ISSUE THREAD

**Issue by Djfe** [mozilla/sumo-playstore-campaign#47]
I'll use this issue, to ask questions, that arose while translating the guidance doc

- Is this string talking about changing app permissions due to updates?
https://crowdin.com/translate/sumo-playstore/936/en-de#1393550

- Where is the following string displayed?
https://crowdin.com/translate/sumo-playstore/936/en-de#1393490

**Comment by couci** [comment]
Just making sure this is the first string right? if yes good catch we are taking this out, it's just a copy paste from the shorter doc

**Comment by Djfe** [comment]
ups 😳 
I copied the links to the document instead of to the string.
In the past Crowdin showed the string link in the browsers address bar, they changed that lately. (now you have to press the 3 dots button next to the strings)

Yes number 2 was the first string of the file.

The first string I listed, was something else though.
I would be glad, if you could take a look :)

```what it is you are asking us to accept with this update```
EDIT: Is "the user" asking: what are the updated app permissions for?
