### ISSUE TITLE
Shortlinks in the doc aren't clickable

### ISSUE THREAD

**Issue by Djfe** [mozilla/sumo-playstore-campaign#49]
Lots of the shortlinks on Google Docs aren't clickable anymore for some reason:
https://docs.google.com/document/d/e/2PACX-1vQds-2DY62ztTCyaoyVr5myp5ZszUFhAyfGueTz5OF9Gi5UibS9LoMxAFkkMhlaH133WF6M3bggD8K4/pub

**Comment by MichaelKohler** [comment]
@couci something for you

**Comment by couci** [comment]
fixed
