### ISSUE TITLE
Permission to Fork this git to create SUMO day campaign

### ISSUE THREAD

**Issue by turtlelovesshoes** [mozilla/sumo-playstore-campaign#67]
@couci @MichaelKohler after being a part of the sprint and working with you both, can we have permission to try forking a few of the pages you worked on here for a Social SUMO Day Sprint? (Dates Oct 23, 24, 25, and two weeks after.) 

Gather interest time would start next week. 
@LucyeoH  
Yuli will reply with interest in helping work on a git for this campaign.

**Comment by yulireyji** [comment]
Hi  @MichaelKohler @couci 

I am interested in helping with the page for the new SUMO DAY

Thanks for all!

**Comment by MichaelKohler** [comment]
I'll have to defer to @couci for this as I have neither the source code nor power to decide on its licensing..

**Comment by MichaelKohler** [comment]
Oh wait, sounds like you want this repo here and therefore the campaign landing page and not the responding tool. Sure, full permission given to reuse as you like as the campaign landing page (this repo) is under MIT license.

**Comment by turtlelovesshoes** [comment]
Thank you!

**Comment by turtlelovesshoes** [comment]
Follow up: closed and used Splash to create the event instead.
